export { default as Home } from './Home'
export { default as Demo } from './Demo'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Welcome } from './Welcome'
